ccflags-y += -Idrivers/media/platform/msm/camera_v2_odin
ccflags-y += -Idrivers/media/platform/msm/camera_v2_odin/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_odin/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_odin/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_ois.o
