ccflags-y += -Idrivers/media/platform/msm/camera_v2_odin
ccflags-y += -Idrivers/media/platform/msm/camera_v2_odin/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_odin/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_odin/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_odin/msm_buf_mgr/
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
