ccflags-y += -Idrivers/media/platform/msm/camera_v2_oscar
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oscar/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oscar/sensor/io
obj-$(CONFIG_MSM_CCI) += msm_cci.o
