ccflags-y += -Idrivers/media/platform/msm/camera_v2_oscar
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oscar/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oscar/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oscar/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oscar/msm_buf_mgr/
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
